engines:
  eslint:
    enabled: true
    channel: "eslint-3"
ratings:
   paths:
   - src/pager.jsx
exclude_paths:
- spec/**/*
- demo/**/*
- demo/bundle.js
- dist/**/*
- img/**/*
- webpack.config.js
- karma.conf.js